In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.array([[5, 6], [7, 8]])

C = A + B

print("First Matrix:")
print(A)

print("Second Matrix:")
print(B)

print("Addition of two Matrices:")
print(C)


First Matrix:
[[1 2]
 [3 4]]
Second Matrix:
[[5 6]
 [7 8]]
Addition of two Matrices:
[[ 6  8]
 [10 12]]
